### ISSUE TITLE
Code comments appearing in wrong color in vim

### ISSUE THREAD

**Issue by prashcr** [mhartington/oceanic-next#25]
In all the below screenshots I'm using iTerm2, `oceanic-next-iterm`, as well as `oceanic-next` in vim.
This issue appears in all filetypes.

**On my Mac**
**reproducable
1) without tmux ($TERM `xterm-256color`)
2) tmux with or without iterm integration ($TERM `screen-256color`)**
![screen shot 2016-08-03 at 10 51 45 am](https://cloud.githubusercontent.com/assets/7514066/17352490/6d82dff8-5969-11e6-828e-b7627eb16271.png)

**SSH'd in to a Debian VPS with same vimrc**
**without tmux ($TERM `xterm-256color`)**
This is what I expect
![screen shot 2016-08-03 at 10 53 55 am](https://cloud.githubusercontent.com/assets/7514066/17352534/d4ce5d36-5969-11e6-80f9-6c3a71d7a21e.png)

**SSH'd in to a Debian VPS with same vimrc**
**tmux, same result with or without iterm integration ($TERM `screen`)**
if I `export TERM=xterm-256color`, it works fine even in tmux
![screen shot 2016-08-03 at 10 55 12 am](https://cloud.githubusercontent.com/assets/7514066/17352566/0c305928-596a-11e6-9fef-ecc257f82c3c.png)

Except comments, everything else looks fine everywhere.
How can I narrow this down?

**Comment by derimagia** [comment]
Have you found any solutions to this? It makes the scheme unusable sadly :(

**Comment by derimagia** [comment]
It looks like the plugin tries to make the text italic which causes issues. See http://stackoverflow.com/questions/5486882/completely-disable-italic-text-in-gvim where the solarized theme makes this an option. Removing the "italic" flag on all items also would work

**Comment by mhartington** [comment]
Hey sorry for the silence on this, been super busy with work. Hmmm, yeah we're using italics in comments and a few other places.

[See this commit](https://github.com/mhartington/oceanic-next/commit/04218baec00a78d26d412bb6e7f799b342a02c6b#diff-e8a060cc160b2d21d9797efdd57a8fb7R199).

I think it may be ok to revert the commit if it's causing issues. Especially since it should be easy to override as well. Give me a bit to push a fix 👍

**Comment by derimagia** [comment]
Awesome thanks for the quick response. I think a setting would be the best option like solarized does.. It looks like it even auto-detects if the terminal supports it: 

https://github.com/altercation/vim-colors-solarized/blob/528a59f26d12278698bb946f8fb82a63711eec21/colors/solarized.vim#L137

I think bold has less issues but it looks like it also has a setting for it to disable it...

**Comment by mhartington** [comment]
Alright. Would you be up for making a PR?

**Comment by derimagia** [comment]
My terminal doesn't currently support italics so I would say for now just remove it. base16 builder would be where it should be added to anyway, yeah?

**Comment by prashcr** [comment]
Thanks!

I think completely removing the feature would be waste of effort, as it looks nice when it does work. I could make a PR in the next couple of days.

I'm a bit confused though. If iTerm doesn't support italics (according to the solarized code), then how does it work for me inside SSH? Does that mean it also depends on which pseudo-tty is running?

**Comment by mhartington** [comment]
These are disabled now by default. You can enable them if your terminal supports it.

**Comment by derimagia** [comment]
iterm2 supporting italics is a relatively recent addition. (See https://github.com/altercation/vim-colors-solarized/pull/65 and https://github.com/altercation/vim-colors-solarized/issues/120). It also depends on what your TERM is set to - See https://github.com/ThomasAdam/tmux/blob/20598dff258da1e96a060adba95e8e05bfdd8b3b/FAQ#L355-L383, which is for tmux but it applies to iterm too since vim can't make things italic without a TERM which has italics

**Comment by prashcr** [comment]
I see. I'm definitely sure my iTerm supports italics since it's the latest available, and it works inside SSH in iTerm, just not locally on my Mac.

As I mentioned above, my TERM was set to xterm-256color. What else could be causing this?

**Comment by mhartington** [comment]
So the overall reason for this is not 100% the terminal, but also the xterm setting. So you have to configure your xterm settings how to use italics

```
xterm-256color-italic|xterm with 256 colors and italic,
        sitm=\E[3m, ritm=\E[23m,
                use=xterm-256color,
                ]]
```

Then, when mixed in with tmux, you also have to set the correct terminal 

https://github.com/mhartington/dotfiles/blob/master/tmux.conf#L26

So there's quite a few moving parts already, then the ssh part is just another layer.

To be honest, I'm not 100% sure why. Maybe the tmux settings?

**Comment by derimagia** [comment]
As far as I understand, that's to add the terminal capability for it.  Look
up termcap for some more info on it, it's kind of interesting.  If you ever
used tputs you're using this

**Comment by olalonde** [comment]
> These are disabled now by default. You can enable them if your terminal supports it.

Has this been reverted somehow? I just updated and seeing

<img width="353" alt="screenshot 2016-10-02 19 16 05" src="https://cloud.githubusercontent.com/assets/416585/19025958/afd34826-88d4-11e6-9b77-b016f97367db.png">

**Comment by olalonde** [comment]
I added echos here:

``` viml
" setup italics {{{
let s:italic = ""
if exists('g:oceanic_next_terminal_italic')
  echo "italic"
  echo g:oceanic_next_terminal_bold
  let s:italic = "italic"

endif
let g:oceanic_next_terminal_italic = get(g:, 'oceanic_next_terminal_italic', 0)
"}}}

" setup bold {{{
let s:bold = ""
if exists('g:oceanic_next_terminal_bold')
  echo "bold"
  echo g:oceanic_next_terminal_bold
  let s:bold = "bold"

endif
let g:oceanic_next_terminal_bold = get(g:, 'oceanic_next_terminal_bold', 0)
"}}}
```

And when I open vim again:

``` sh
$ vim ~/.vim/bundle/oceanic-next/colors/OceanicNext.vim
italic
0
bold
0
Press ENTER or type command to continue
```

I'm not setting those vars in my .vimrc so not sure what's going on here.

**Comment by olalonde** [comment]
Ok, so it looks like `/.vim/bundle/oceanic-next/colors/OceanicNext.vim` is sourced twice and the first time it is sourced, it sets `g:oceanic_next_terminal_bold` and `g:oceanic_next_terminal_italic` to 0 and second time it is sourced, `exists('g:oceanic_next_terminal_italic')` evaluates to `true`.

**Comment by olalonde** [comment]
Wow, that was subtle... 

Replacing (in my .vimrc)

``` viml
colorscheme OceanicNext
set background=dark
```

with

``` viml
set background=dark
colorscheme OceanicNext
```

fixed the issue

**Comment by zshihang** [comment]
the solution I found for this **italic** thing is adding two lines in vimrc: 
```
set t_ZH=^[[3m
set t_ZR=^[[23m
```
"^[" is escape character entered by C-v Esc in INSERT mode.

SSHing works because the values of t_ZH and t_ZR are correct. You can see the values by `:set termcap`. While in mac, the values are different and that's why it is weirdly showed.

Mac:
<img width="243" alt="screen shot 2017-10-09 at 2 27 45 pm" src="https://user-images.githubusercontent.com/9028490/31353185-89751510-acff-11e7-922f-f2883787c75c.png">

SSHing Debian;
<img width="196" alt="screen shot 2017-10-09 at 2 29 17 pm" src="https://user-images.githubusercontent.com/9028490/31353213-a152f6c0-acff-11e7-82f2-9f3dbeb40a3f.png">

**Comment by khacluan** [comment]
I tried to set in the `.vimrc`

```vim
set t_ZH=
set t_ZR=
colorscheme OceanicNext
```
and it worked for me
