### ISSUE TITLE
background unsettable

### ISSUE THREAD

**Issue by jonpolak** [mhartington/oceanic-next#27]
The background color makes everything unreadable. I tried both true-color and 256 as per the image below. 
![image](https://cloud.githubusercontent.com/assets/1812219/17869619/eb111c24-6868-11e6-9f11-fb8aad706bef.png)

**Comment by mhartington** [comment]
What terminal is that? Does it support true colors? I'm guessing not since this is a similar visual to the default terminal on mac

![screen shot 2016-08-22 at 4 06 10 pm](https://cloud.githubusercontent.com/assets/2835826/17869697/78fbcd4a-6882-11e6-9fe9-2785e7f77e9f.png)

Iterm on the left, Terminal.app on the right.

**Comment by jonpolak** [comment]
it's mate-terminal ... I nested the set termguicolors within in an `if` (as you indicated in the README). 

> > UPDATE  - removing the `if(has("termguicolors"))` and the `set termguicolors` gives this (below) -- yes it seems like the term reports that 24bit color is available when it isn't --
> > ![image](https://cloud.githubusercontent.com/assets/1812219/17869809/c75ce17c-6869-11e6-86aa-6f455fdf0245.png)

**Comment by mhartington** [comment]
Closing then. Mate terminal does not support true colors. 

Cheers!
