### ISSUE TITLE
Bold setting doesn't work

### ISSUE THREAD

**Issue by aaaxx** [mhartington/oceanic-next#84]
Using the italics and bold configuration from the readme, italics can be configured fine, but bold is always enabled.

From what little I can figure out in Vimscript after some poking around, it seems that `bold` variable is missing the `s:` prefix throughout both `OceanicNext.vim` and `OceanicNextLight.vim`.

**Comment by mroavi** [comment]
I also noticed something similar. I noticed that the Vim variables are shown in bold text even if `let g:oceanic_next_terminal_bold = 0` is defined. The reason is that the highlight group `vimVar` links to `Identifier`
![image](https://user-images.githubusercontent.com/19517248/80610389-98d3ae80-8a39-11ea-8eed-9de13822396d.png)
And `Identifier` is being defined as `bold`:
![image](https://user-images.githubusercontent.com/19517248/80610566-cc163d80-8a39-11ea-9928-c1e211d8d689.png)
The strange thing is that `Identifier` is not being defined as `bold` inside `colors/OceanicNext.vim`
![image](https://user-images.githubusercontent.com/19517248/80610827-1d263180-8a3a-11ea-9829-6db5cae638af.png)
Any idea why the `Identifier` hi group is showing up in bold text?

Adding `'NONE'` in the `gui` field disables Vim variables from showing up in bold text:
![image](https://user-images.githubusercontent.com/19517248/80612241-fe289f00-8a3b-11ea-8d4d-e5407bd446dc.png)

**Comment by mhartington** [comment]
In vim colorschemes, it's common to have this snippet in place

```
  set background=dark
  hi clear
  if exists("syntax_on")
    syntax reset
  endif
```

Which surprisingly is responsible for making `Identifier` get "bold".  The logic here is that vim provides a lot of colors already out of the box, so instead of trying to customize everything, change what you need. 

I think i'm going to close this as it's less of a bug with the theme and more just how vim works. If you're up for changing the default and sending a PR, that would be great too.

**Comment by aaaxx** [comment]
So how can Vim's default bold be turned off? For example, language keywords are shown in bold for me.

Edit: Never mind. I figured out that the default Statement group and some others were causing it and disabled them:

```viml
highlight Statement  gui=NONE cterm=NONE term=NONE
```
